on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          show-progress: false
      - uses: pnpm/action-setup@v5
        with:
          cache: true
          run_install: |
            - args: [--prefer-offline, --frozen-lockfile]
      - run: pnpm check

  e2e:
    needs: lint
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          show-progress: false
      - uses: pnpm/action-setup@v5
        with:
          cache: true
          run_install: |
            - args: [--prefer-offline, --frozen-lockfile]
      - uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
      - run: pnpm build-only
      - run: pnpm exec playwright install --with-deps
      - run: pnpm test:e2e --only-changed=origin/${{ github.base_ref }}
